# PostgreSQL Client Authentication Configuration File

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# local socket: supatype_admin uses password, OS users use peer map
local all  supatype_admin     scram-sha-256
local all  all                peer map=supatype_map

# loopback
host  all  all  127.0.0.1/32  trust
host  all  all  ::1/128       trust

# external connections (password required)
host  all  all  0.0.0.0/0     scram-sha-256
host  all  all  ::0/0         scram-sha-256
