# PostgreSQL User Name Maps

# MAPNAME       SYSTEM-USERNAME         PG-USERNAME
supatype_map  postgres   postgres
supatype_map  postgres   supatype_admin
supatype_map  root       postgres
supatype_map  root       supatype_admin
supatype_map  ubuntu     postgres

# supatype service users
supatype_map  gotrue     supatype_auth_admin
supatype_map  postgrest  authenticator
