/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2069
CREATE SCHEMA IF NOT EXISTS supacache; /* pg_keyspace::supacache */
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2202
-- pg_keyspace::supacache::bench_get
CREATE  FUNCTION supacache."bench_get"(
	"key" TEXT, /* &str */
	"val" bytea, /* &[u8] */
	"iters" bigint /* i64 */
) RETURNS double precision /* f64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bench_get_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2108
-- pg_keyspace::supacache::del
CREATE  FUNCTION supacache."del"(
	"key" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'del_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2089
-- pg_keyspace::supacache::set
CREATE  FUNCTION supacache."set"(
	"key" TEXT, /* &str */
	"val" bytea, /* &[u8] */
	"ttl_seconds" bigint DEFAULT 0 /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2397
-- pg_keyspace::supacache::rowcache_stats
CREATE  FUNCTION supacache."rowcache_stats"() RETURNS TABLE (
	"entries" bigint,  /* i64 */
	"hits" bigint,  /* i64 */
	"misses" bigint,  /* i64 */
	"data_used" bigint,  /* i64 */
	"data_cap" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rowcache_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2124
-- pg_keyspace::supacache::ping
CREATE  FUNCTION supacache."ping"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ping_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2422
-- pg_keyspace::supacache::stats
CREATE  FUNCTION supacache."stats"() RETURNS TABLE (
	"partition" INT,  /* i32 */
	"entries" bigint,  /* i64 */
	"hits" bigint,  /* i64 */
	"misses" bigint,  /* i64 */
	"evictions" bigint,  /* i64 */
	"sets" bigint,  /* i64 */
	"tombstones" bigint,  /* i64 */
	"rehashes" bigint,  /* i64 */
	"data_used" bigint,  /* i64 */
	"data_cap" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2321
-- pg_keyspace::supacache::rowcache_unregister
CREATE  FUNCTION supacache."rowcache_unregister"(
	"tbl" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rowcache_unregister_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2283
-- pg_keyspace::supacache::rowcache_register
CREATE  FUNCTION supacache."rowcache_register"(
	"tbl" TEXT, /* &str */
	"pk_attnum" INT /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rowcache_register_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2170
-- pg_keyspace::supacache::ring_stats
CREATE  FUNCTION supacache."ring_stats"() RETURNS TABLE (
	"pushed" bigint,  /* i64 */
	"dropped" bigint,  /* i64 */
	"backlog_bytes" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ring_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2103
-- pg_keyspace::supacache::incr
CREATE  FUNCTION supacache."incr"(
	"key" TEXT, /* &str */
	"by" bigint DEFAULT 1 /* i64 */
) RETURNS bigint /* core::option::Option<i64> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'incr_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2080
-- pg_keyspace::supacache::get
CREATE  FUNCTION supacache."get"(
	"key" TEXT /* &str */
) RETURNS bytea /* core::option::Option<alloc::vec::Vec<u8>> */
STRICT STABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2376
-- pg_keyspace::supacache::rowcache_cached_has_external
CREATE  FUNCTION supacache."rowcache_cached_has_external"(
	"tbl" TEXT, /* &str */
	"pk" anyelement /* pgrx::datum::anyelement::AnyElement */
) RETURNS bool /* core::option::Option<bool> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rowcache_cached_has_external_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2224
-- pg_keyspace::supacache::bench_set
CREATE  FUNCTION supacache."bench_set"(
	"key" TEXT, /* &str */
	"val" bytea, /* &[u8] */
	"iters" bigint /* i64 */
) RETURNS double precision /* f64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bench_set_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2113
-- pg_keyspace::supacache::getset
CREATE  FUNCTION supacache."getset"(
	"key" TEXT, /* &str */
	"val" bytea /* &[u8] */
) RETURNS bytea /* core::option::Option<alloc::vec::Vec<u8>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'getset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2256
-- pg_keyspace::supacache::warm
CREATE  FUNCTION supacache."warm"(
	"n" bigint, /* i64 */
	"val_bytes" bigint /* i64 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'warm_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2342
-- pg_keyspace::supacache::rowcache_put
CREATE  FUNCTION supacache."rowcache_put"(
	"tbl" TEXT, /* &str */
	"pk" anyelement /* pgrx::datum::anyelement::AnyElement */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rowcache_put_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2240
-- pg_keyspace::supacache::bench_incr
CREATE  FUNCTION supacache."bench_incr"(
	"key" TEXT, /* &str */
	"iters" bigint /* i64 */
) RETURNS double precision /* f64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bench_incr_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2135
-- pg_keyspace::supacache::set_credential
CREATE  FUNCTION supacache."set_credential"(
	"username" TEXT, /* &str */
	"secret" TEXT, /* &str */
	"role" TEXT, /* &str */
	"tenant" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_credential_wrapper';
/* </end connected objects> */

